spring:
  application:
    name: jspprac2
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2-database
  datasource:
    url: jdbc:mysql://localhost:3306/jspprac2?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1324
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false